# 语法

1. 基本

   ```javascript
   //Promise对象是一个构造函数，接受一个函数作为参数，这个函数有resolve，reject两个函数作为参数，resolve执行表示将Promise状态从pending->fulfilled,reject执行则表示将Promise状态从pending->rejected
   const p = new Promise((resolve, reject) => { //生成Promise实例,会立即执行
       if (true) { //异步操作成功
           resolve('fulfilled'); //结果作为参数传递出去
       } else { //异步操作失败
           reject('rejected'); //错误作为参数传递出去
       }
   });
   ```

2.  then--实例状态改变时的回调，返回一个新的Promise实例，可以链式调用

   ```javascript
   //then方法接受两个函数作为参数
   p.then(
       value => { //fulfilled状态回调函数
           console.log(value);
       },
       error => { //rejected状态回调函数
           console.log(error);
       }
   );
   ```

   ```javascript
   //Promise实例立即执行
   console.log('我是甲');
   const p1 = new Promise(reso => {
       console.log('立即');
       reso('我是reso'); //晚于本轮循环的同步任务执行
       console.log('执行');
   });
   p1.then(res => {
       console.log(res);
   });
   console.log('我是乙');
   //我是甲
   //立即
   //执行
   //我是乙
   //我是reso
   ```

   ```javascript
   //resolve函数是另一个Promise
   const p1 = new Promise((reso, rej) => {
       setTimeout(() => {
           rej('p1的失败');
       }, 4000);
   });
   const p2 = new Promise((reso, rej) => {
       setTimeout(() => {
           reso(p1); //p2的异步操作结果是p1,p1的状态决定了p2的状态
       }, 1000);
   });
   p2.then(
       res => {
           console.log(res);
       },
       err => {
           console.log(err); //1+3秒后打印'p1的失败'
       }
   );
   ```

   ```javascript
   const state = 1;
   function step1(reso, rej) {
       console.log('开始洗菜');
       if (state == 1) {
           reso('洗菜完成');
       } else {
           rej('洗菜失败');
       }
   }
   function step2(reso, rej) {
       console.log('开始吃饭');
       if (state == 1) {
           reso('吃饭完成');
       } else {
           rej('吃饭失败');
       }
   }
   function step3(reso, rej) {
       console.log('开始洗碗');
       if (state == 1) {
           reso('洗碗完成');
       } else {
           rej('洗碗失败');
       }
   }
   new Promise(step1)
       .then(v => {
       console.log(v);
       return new Promise(step2);
   })
       .then(v => {
       console.log(v);
       return new Promise(step3);
   })
       .then(v => {
       console.log(v);
   });
   //开始洗菜
   //洗菜完成
   //开始吃饭
   //吃饭完成
   //开始洗碗
   //洗碗完成
   ```

3.  catch--发生错误时的回调，相当于then(null,reject)或(undefined,reject)

   ```javascript
   //Promise对象的错误具有冒泡性质，会一直向后传递,直到被捕获。没捕获处理的话，也不会影响Promise外层代码
   const ps = new Promise((reso, rej) => {
       if (false) {
           reso('succ');
       } else {
           rej('fail');
       }
   });
   ps.then(
       res => {
           let a = 90;
           let a = 909;
           console.log(res);
       },
       err => { //有这个reject函数，便不会执行catch函数，除非手动throw error了
           console.log('err:', err);
           throw new Error('错错错err');
       }
   ).catch(error => { //catch方式捕获错误更好，更接近同步写法
       console.log('catch:', error);
   });
   
   ```

4.  finally--无论Promise对象最后的状态是fulfiiled还是rejected，都会执行。相当于then(()=>{要执行的语句},()=>{要执行的语句})

   ```javascript
   p.then(v=>{..}).finally(()=>{..}) //finally方法的回调函数不接受任何参数
   
   //finally方法返回原来的值
   Promise.resolve(1).then(() => {
     console.log('then');
   }).then(v => console.log(v));
   //then
   //undefined
   
   Promise.resolve(2).finally(() => {
     console.log('finally');
   }).then(v => console.log(v));
   //finally
   //2
   ```

5. all--多个Promise实例(不是的话调用Promise.resolve方法处理)包装成一个新的Promise实例。都成功(fulfilled)则成功，返回成功的数组。失败(rejected)任何一个，返回最先失败的那个。

   ```javascript
   let a = true,
       b = true,
       c = true;
   
   const pa = new Promise((reso, rej) => {
       if (a) {
           reso('pa:true');
       } else {
           rej('pa:false');
       }
   });
   const pb = new Promise((reso, rej) => {
       if (b) {
           reso('pb:true');
       } else {
           rej('pb:false');
       }
   });
   const pc = new Promise((reso, rej) => {
       if (c) {
           reso('pc:true');
       } else {
           rej('pc:false');
       }
   });
   
   const pall = Promise.all([pa, pb, pc])
   .then(res => {
       console.log(res);
   })
   .catch(err => {
       console.log(err);
   });
   //情况-》pa,pb,pc的状态都变为fulfilled,此时pall的状态才变成fulfilled
   //res->["pa:true", "pb:true", "pc:true"]
   
   //情况-》只要有一个变为rejected，那pall的状态就会变成rejected
   //比如b=false，c=false。err->"pb:false"。返回最先被reject的实例的值
   
   //注意，若作为pall参数的实例自身定义了catch方法，如b=false，按说返回“pb:false”,但
   const pb = new Promise((reso, rej) => {
       if (b) {
           reso('pb:true');
       } else {
           rej('pb:false');
       }
   }).catch(() => {});
   //则不会触发pall的catch方法，这时返回["pa:true", undefined, "pc:true"]
   ```

6. race--多个Promise实例(不是的话调用Promise.resolve方法处理)包装成一个新的Promise实例。返回最先改变状态的那个

   ```javascript
   const prace = Promise.race([pa, pb, pc])
   .then(res => {
       console.log(res);
   })
   .catch(err => {
       console.log(err);
   });
   //pa:true
   
   const prace1=Promise.race([
       ajaxP(...),
       new Promise((reso,rej)=>{
           setTimeout(()=>rej('请求超过9s报错'),5000)
       })
   ])
   prace1.then(..).catch(..)    
   //9s内ajaxP没返回结果，prace1的状态就会变为rejected,从而触发catch方法
   ```

   